### ISSUE TITLE
Execute module related cmds?

### ISSUE THREAD

**Issue by srbharadwaj** [jtdub/netlib#9]
Hey , this is a nice tool, few suggestions
1) ssh.command(cmd) , here the argument is only a string why not a list which takes a list of cmds?
2) how about executing module related cmds?

**Comment by jtdub** [comment]
It would be simple enough to do:

    commands = ['config t', 'vlan 200', 'name VLAN-200', 'end', 'copy run start']

    def ssh.command_list(self, commands):
        import time
        for cmd in commands:
            self.client_conn.sendall(cmd + "\n")
            not_done = True
            output = ""
            self.clear_buffer()
            while not_done:
                time.sleep(float(self.delay))
                if self.client_conn.recv_ready():
                    output += self.client_conn.recv(self.buffer)
                else:
                    not_done = False
        return output

Here is how I'm currently using netlib, to do what you propose:

https://github.com/jtdub/pyMultiChange/blob/master/multi.py#L73

**Comment by jtdub** [comment]
I've implemented the list of commands request. It's available for both SSH and Telnet classes:

https://github.com/jtdub/netlib/blob/master/netlib/conn_type.py#L61
